### ISSUE TITLE
无法编译啊，jdk8和11都试过了

### ISSUE THREAD

**Issue by nop4LOL** [halo-sigs/plugin-photos#2]

**Comment by JohnNiang** [comment]
有没有可能用 JDK 17 就可以编译了呢。

/kind support

**Comment by nop4LOL** [comment]
> 有没有可能用 JDK 17 就可以编译了呢。
> 
> /kind support

woc，竟然回复我了，是的，换了jdk17已经编译好了，不过没法使用，开启后，访问 /photos 提示404，主题是有 photos.html 文件的，这是怎么回事，是插件中没有注册路由么还是？希望告知如何解决~

**Comment by nop4LOL** [comment]
> 有没有可能用 JDK 17 就可以编译了呢。
> 
> /kind support

还是说该插件还没有彻底开发完成，只做了console的部分，适配的路由还没做

**Comment by JohnNiang** [comment]
当前插件还没有发布一个版本，还处于开发状态。

可以先看看 PR：<https://github.com/halo-sigs/plugin-photos/pull/1>。

**Comment by nop4LOL** [comment]
> 当前插件还没有发布一个版本，还处于开发状态。
> 
> 可以先看看 PR：#1。

hah ，我就是编译的最新pr1，你之前未合并的代码，但是访问 /photos 是404，请问正常的插件发布大概还要多久，就是路由什么的都搞好~~

**Comment by JohnNiang** [comment]
有任何问题可以直接在 PR https://github.com/halo-sigs/plugin-photos/pull/1 下评论。

有兴趣的话，也可以参考一下：<https://github.com/halo-sigs/plugin-links/blob/65168ebae32bea61d8f0b8e1370d5ac392e64d1d/src/main/java/run/halo/links/LinkRouter.java>。

**Comment by nop4LOL** [comment]
> 有任何问题可以直接在 PR #1 下评论。
> 
> 有兴趣的话，也可以参考一下：https://github.com/halo-sigs/plugin-links/blob/65168ebae32bea61d8f0b8e1370d5ac392e64d1d/src/main/java/run/halo/links/LinkRouter.java。

LinkRouter.java 这个我看过了，也加上了这个文件，把link都改成了photo，但是报错 photoGroups() 没有这个函数，于是我在map函数中去掉了 photoGroup这个函数，重新打包没问题了，但是访问 /photos 是纯纯乱码，js、css也不渲染，整个页面都是模板函数 {{xxxx..xxxx}} 这些标签，能发我一份正确的 photoRouter.java 文件么

**Comment by ruibaby** [comment]
目前此插件已经开发完毕，可以再试试。

/close
