### ISSUE TITLE
不显示操作按钮

### ISSUE THREAD

**Issue by appleCow** [halo-sigs/plugin-photos#24]
Halo版本2.10.0-SNAPSHOT，安装插件后不显示操作按钮（如添加），看[管理员也有这个权限，新建用户赋予权限也不显示。
![微信截图_20231007113848](https://github.com/halo-sigs/plugin-photos/assets/7857181/42ed7e2d-b2b6-47ee-9e59-69acbea836d7)
![微信截图_20231007113859](https://github.com/halo-sigs/plugin-photos/assets/7857181/a2465922-116e-45f5-95df-e1fa8dccc676)

**Comment by ruibaby** [comment]
将在 https://github.com/halo-sigs/plugin-photos/pull/22 修复。
