### ISSUE TITLE
图库无法通过Personal Access Tokens 认证 api发布图片

### ISSUE THREAD

**Issue by jiewenhuang** [halo-sigs/plugin-photos#31]
同样的token，已经勾选所有权限
<img width="749" alt="image" src="https://github.com/halo-sigs/plugin-photos/assets/68629578/af857194-5e6b-4705-81d9-6ef143c2f31e">
可以通过这个token认证，发布瞬间信息，但是无法发布图库。
 moment 用的是 /apis/api.plugin.halo.run/v1alpha1/plugins/PluginMoments/moments，
但是图库好像只有对应的get方法，没有post
<img width="1472" alt="image" src="https://github.com/halo-sigs/plugin-photos/assets/68629578/72c6e73a-5ee2-4b5d-bfc2-0cf5a145cb8a">
看后台请求用的/apis/core.halo.run/v1alpha1/photos ，但是这个接口，token认证401，账号密码认证正常。
<img width="933" alt="image" src="https://github.com/halo-sigs/plugin-photos/assets/68629578/dea01906-d1c5-432d-af09-d3c1b2f3f7ac">

**Comment by JohnNiang** [comment]
Hi @jiewenhuang ，请参考一下图库的角色模板规则（这里定义了角色可以操作哪些 API 组的哪些资源）：

https://github.com/halo-sigs/plugin-photos/blob/845bc99e73e7ce262d5b201ce3d78b99df542d6c/src/main/resources/extensions/roleTemplate.yaml#L1-L38

**Comment by LIlGG** [comment]
目前图库没有对 `core.halo.run` 组资源定义角色模板，因此只有超级管理员可以访问此资源。需要对 `core.halo.run` 添加角色模板。

/kind bug
