### ISSUE TITLE
分页功能无效问题

### ISSUE THREAD

**Issue by jiewenhuang** [halo-sigs/plugin-photos#40]
halo2.13-rc-1 halo2.13.1  
更新版本后，分页功能似乎不起作用了，会把所有图片都加载出来。设置分页也是无效的。
<img width="1436" alt="image" src="https://github.com/halo-sigs/plugin-photos/assets/68629578/a2f5644e-cb64-4fe8-a6e2-138ef9373ae2">  

<img width="793" alt="image" src="https://github.com/halo-sigs/plugin-photos/assets/68629578/d7aa3a37-d6b2-4d2f-9393-d878c7f63310">

**Comment by LIlGG** [comment]
当使用 `/photos/page/{page}` 分页并且在其中使用 `${groups}` 获取数据时，确实会获取到所有图片。

我阅读了 Joe 主题的代码，主题端使用 `${groups}` 的方式是不正确的，从 `${groups}` 获取图片应当只发生在非分页的情况下。分页情况下不能使用从 group 中获取到的 photos，而应该使用类似于 `photos/page/1?group=photo-group-UEcvi` 这样的路由。

或者你可以使用 
```
<ul>
    <li th:each="photo : ${photos.items}">
        <img th:src="${photo.spec.url}" th:alt="${photo.spec.displayName}" width="280">
    </li>
</ul>
<div th:if="${photos.hasPrevious() || photos.hasNext()}">
   <a th:href="@{${photos.prevUrl}}">
      <span>上一页</span>
   </a>
   <span th:text="${photos.page}"></span>
   <a th:href="@{${photos.nextUrl}}">
      <span>下一页</span>
   </a>
</div>
```

来获取当页的图片。

**Comment by jiewenhuang** [comment]
好的，非常感谢！
