### ISSUE TITLE
[BUG] 图库页面设置缺少顶部大图链接配置，移动端模式切换按钮无法使用

### ISSUE THREAD

**Issue by carolcoral** [halo-sigs/plugin-photos#45]
from issue [https://github.com/chengzhongxue/halo-theme-hao/issues/759](https://github.com/chengzhongxue/halo-theme-hao/issues/759)

**Comment by chengzhongxue** [comment]
这个是主题里的东西，跟图库插件没关系

**Comment by LIlGG** [comment]
该问题与图库插件没有关联。

原 issue 的提交者已经描述的很清晰了，是由于主题中使用了 `theme.config.photos.backgroundImg` 配置项，但主题的 `settings.yaml` 中并未提供此配置项导致。建议主题进行修复。

/close
